//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PrimaryPhone { get; set; }
        public string HomePhone { get; set; }
        public string Fax { get; set; }
        public string CellNo { get; set; }
        public Nullable<int> ContactType { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string CompanyName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdateDate { get; set; }

        public virtual AspNetUser ContactCreatedBy { get; set; }
        public virtual AspNetUser ContactUpdatedBy { get; set; }
        
        public virtual ICollection<Inquiry> Inquiries { get; set; }
        
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
