//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        public Inquiry()
        {
            this.InquiryDetails = new HashSet<InquiryDetail>();
        }
    
        public int InquiryID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<System.DateTime> InquiryDate { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ContactResponse { get; set; }
        public string UserComments { get; set; }
    
        public virtual ICollection<InquiryDetail> InquiryDetails { get; set; }
    }
}
