//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Models.DomainModels
{  
    public partial class NotificationRecipient
    {
        public long Id { get; set; }
        public long NotificationId { get; set; }
        public string UserId { get; set; }
        public bool IsRead { get; set; }
    
        public virtual AspNetUser RecipientUser { get; set; }
        public virtual Notification Notification { get; set; }
    }
}
