//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int ProductCategoryID { get; set; }
        public string CatName { get; set; }
        public string ShortDescription { get; set; }
        public string DetailDescription { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public Nullable<int> ParentCatID { get; set; }
    }
}
