//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace TMD.Models.DomainModels
{

    public partial class ProductCategory
    {
        public int ProductCategoryID { get; set; }
        public string CatName { get; set; }
        public string ShortDescription { get; set; }
        public string DetailDescription { get; set; }
        public bool IsParent { get; set; }
        public int? ParentCatID { get; set; }

        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
        public virtual ProductCategory ProductCategoryParent { get; set; }
    }
}
