//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace TMD.Models.DomainModels
{

    public class ProductCategory
    {
        public int ProductCategoryID { get; set; }
        public string CatName { get; set; }
        public string ShortDescription { get; set; }
        public string DetailDescription { get; set; }
        public bool IsParent { get; set; }
        public int? ParentCatID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }

        public virtual AspNetUser CreatedByUser { get; set; }
        public virtual AspNetUser UpdatedByUser { get; set; }
        
        public virtual ICollection<Product> Products { get; set; }
        
        public virtual ICollection<ProductCategory> SubProductCategories { get; set; }
        public virtual ProductCategory ParentProductCategory { get; set; }
    }
}
