//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTechSpec
    {
        public int ProductTechSpecsId { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string SpecName { get; set; }
        public string SpecValue { get; set; }
    }
}
