//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMD.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteID { get; set; }
        public string QuoteReferenceNo { get; set; }
        public string Subject { get; set; }
        public string PaymentTerms { get; set; }
        public string DeliveryTerms { get; set; }
        public string InstallationTerms { get; set; }
        public string FreeServiceTerms { get; set; }
        public string WarrantyTerms { get; set; }
        public string ValidityTerms { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Make { get; set; }
        public Nullable<int> ModelId { get; set; }
    }
}
